name: Quality Check
on: [push, pull_request]
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - feature/ci-cd
  pull_request:
    branches:
      - *
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check Formatting
        run: ./gradlew ktlint

      - name: Execute jUnit
        run: ./gradlew test
